
POST {{baseUrl}}/token
Authorization: Basic {{authorization}}


###
GET {{baseUrl}}/cases
Accept: application/json
Authorization: Bearer {{acessToken}}

###
GET  {{baseUrl}}/casesSuspected
Accept: application/json
Authorization: Bearer {{acessToken}}

###
GET {{baseUrl}}/casesConfirmed
Accept: application/json
Authorization: Bearer {{acessToken}}

###
GET {{baseUrl}}/deaths
Accept: application/json
Authorization: Bearer {{acessToken}}

###
GET {{baseUrl}}/recovered
Accept: application/json
Authorization: Bearer {{acessToken}}

