//request for all countries data with day by day updates included
###
GET {{baseUrl}}/summary 

//India States Data of all dates
###   
GET {{baseUrl}}/live/country/India


###
GET {{baseUrl}}/total/country/India

###

GET {{baseUrl}}/world/total

